fos_rest:
  body_converter:
    enabled: true
  allowed_methods_listener: true
  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ 'json', 'xml' ] }
