nelmio_api_doc:
  documentation:
    info:
      title: Symfony Timetrack Test App
      description: Symfony Timetrack Test App API docs
      version: 1.0.0
    #    securityDefinitions:
    #      Bearer:
    #        type: apiKey
    #        description: 'Authorization: Bearer {jwt}'
    #        name: Authorization
    #        in: header
    paths:
      /api/auth/login:
        post:
          operationId: postCredentialsItem
          summary: Get JWT token to login.
          requestBody:
            description: Create new JWT Token
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Credentials'
          responses:
            '200':
              description: Get JWT token
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Token'
            '401':
              description:
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/BadCredentials'
    components:
      schemas:
        Token:
          type: object
          properties:
            token:
              type: string
              readOnly: true
        Credentials:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
        BadCredentials:
          type: object
          properties:
            code:
              type: integer
              example: 401
            message:
              type: string
              example: "Invalid credentials."
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
