nelmio_api_doc:
  documentation:
    info:
      title: Symfony Timetrack Test App
      description: Symfony Timetrack Test App API docs
      version: 1.0.0
    paths:
      /api/auth/login:
        post:
          tags:
            - Auth
          summary: Login user
          description: Login user in the system
          security: []
          requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Credentials'
          responses:
            '200':
              description: Get JWT token
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Token'
            '401':
              description: Invalid credentials
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/BadCredentials'
    components:
      schemas:
        Token:
          type: object
          properties:
            token:
              type: string
              readOnly: true
              example: exampleTokenString
        Credentials:
          type: object
          properties:
            email:
              type: string
              example: example@domain.com
            password:
              type: string
              example: somepassword
        BadCredentials:
          type: object
          properties:
            code:
              type: integer
              example: 401
            message:
              type: string
              example: "Invalid credentials."
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: [ ]
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
