version: '3.8'

volumes:
  data-volume:

services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    environment:
      NGINX_PORT: ${NGINX_PORT}
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './:/usr/src/app'
    restart: on-failure
    environment:
      LOCAL_USER: ${LOCAL_USER}
    env_file:
      - .env
      - .env.local
    user: ${LOCAL_USER}